import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fsSource, resolveModule } from "@inklyre/oes-core";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { generateFromPlan } from "../src/generate.js";
import { planYoutubeImport, type ImportPlan } from "../src/plan.js";
import type { YoutubePlaylistData } from "../src/youtube-api.js";

const playlist: YoutubePlaylistData = {
  playlistId: "PLtest",
  playlistUrl: "https://www.youtube.com/playlist?list=PLtest",
  title: "Learn Widgets",
  description: "A course on widgets",
  videos: [
    {
      videoId: "vid1",
      title: "Part 1: Intro",
      description: "d1",
      durationSeconds: 600,
      thumbnailUrl: undefined,
      chapters: [],
    },
    {
      videoId: "vid2",
      title: "Part 2: Advanced",
      description: "d2",
      durationSeconds: 300,
      thumbnailUrl: undefined,
      chapters: [],
    },
  ],
};

let dir: string;

beforeEach(async () => {
  dir = await mkdtemp(join(tmpdir(), "oes-import-youtube-"));
});

afterEach(async () => {
  await rm(dir, { recursive: true, force: true });
});

async function readJson(path: string): Promise<unknown> {
  return JSON.parse(await readFile(path, "utf8"));
}

describe("generateFromPlan", () => {
  it("produces a tree @inklyre/oes-core's resolveModule can walk end-to-end with no errors", async () => {
    const plan = await planYoutubeImport(playlist);
    await generateFromPlan(plan, dir);

    const { data, errors } = await resolveModule(fsSource(dir), "module.json");
    expect(errors).toEqual([]);
    expect(data?.lessons).toHaveLength(2);
    expect(data?.lessons[0].items[0]).toMatchObject({ type: "video" });
  });

  it("writes a valid module.json, one lesson.json and video.json per video", async () => {
    const plan = await planYoutubeImport(playlist);
    const result = await generateFromPlan(plan, dir);

    expect(result.lessonCount).toBe(2);
    expect(result.files).toContain("module.json");

    const moduleDoc = (await readJson(join(dir, "module.json"))) as { lessons: Array<{ id: string; path: string }> };
    expect(moduleDoc.lessons).toHaveLength(2);

    const firstLessonId = plan.module.lessons[0].id;
    const lessonDoc = (await readJson(
      join(dir, "lessons", firstLessonId, "lesson.json"),
    )) as { items: Array<{ type: string; path: string }> };
    expect(lessonDoc.items[0].type).toBe("video");

    const videoId = plan.module.lessons[0].video.id;
    const videoDoc = (await readJson(
      join(dir, "lessons", firstLessonId, "video-lessons", videoId, "video.json"),
    )) as { video_url: string; duration_mins: number; source: { platform: string } };
    expect(videoDoc.video_url).toBe("https://www.youtube.com/watch?v=vid1");
    expect(videoDoc.duration_mins).toBe(10);
    expect(videoDoc.source.platform).toBe("YouTube");
  });

  it("removes a stale lesson folder for a video no longer in the plan on regeneration", async () => {
    const fullPlan = await planYoutubeImport(playlist);
    await generateFromPlan(fullPlan, dir);
    const staleLessonId = fullPlan.module.lessons[1].id;

    const trimmedPlan: ImportPlan = {
      ...fullPlan,
      module: { ...fullPlan.module, lessons: [fullPlan.module.lessons[0]] },
    };
    await generateFromPlan(trimmedPlan, dir);

    await expect(readFile(join(dir, "lessons", staleLessonId, "lesson.json"), "utf8")).rejects.toThrow();
  });

  it("refuses to overwrite an existing directory not produced by this importer, without force", async () => {
    await mkdir(dir, { recursive: true });
    await writeFile(join(dir, "module.json"), JSON.stringify({ ocf_version: "0.3.0", id: "x", title: "x" }));

    const plan = await planYoutubeImport(playlist);
    await expect(generateFromPlan(plan, dir)).rejects.toThrow(/Refusing to overwrite/);
  });

  it("overwrites with force: true", async () => {
    await mkdir(dir, { recursive: true });
    await writeFile(join(dir, "module.json"), JSON.stringify({ ocf_version: "0.3.0", id: "x", title: "x" }));

    const plan = await planYoutubeImport(playlist);
    const result = await generateFromPlan(plan, dir, { force: true });
    expect(result.lessonCount).toBe(2);
  });

  it("writes into a directory previously generated by this importer without needing force", async () => {
    const plan = await planYoutubeImport(playlist);
    await generateFromPlan(plan, dir);
    // Re-running against the same directory (the normal "playlist updated" flow) must not require force.
    await expect(generateFromPlan(plan, dir)).resolves.toMatchObject({ lessonCount: 2 });
  });
});
